matrix:
  include:
  - sudo: required
    branches: only: master
  - sudo: false
    branches: only: matrix

env:
  - SCRIPT="echo first Script"
  - SCRIPT="echo second Script"
  - SCRIPT="ls -la"
  
script: $SCRIPT
  
