language: java  

matrix:
  include:
  - jdk: oraclejdk8
    env: EXAMPLE_ENV_VAR=version8 
  - jdk: oraclejdk9
    env: EXAMPLE_ENV_VAR=version9 
      
script: - if [[ "${EXAMPLE_ENV_VAR}" = "version9" ]]; then echo "HAHAHAHHA"; fi
